FROM azul/zulu-openjdk:21

ARG JAR_FILE=/target/ecommerce-notification-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} notification-service.jar

ENTRYPOINT ["java","-jar","notification-service.jar", "--server.port=8080"]