/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ionutbalosin.training.ecommerce.message.schema.payment;
@org.apache.avro.specific.AvroGenerated
public enum PaymentCurrency implements org.apache.avro.generic.GenericEnumSymbol<PaymentCurrency> {
  EUR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentCurrency\",\"namespace\":\"ionutbalosin.training.ecommerce.message.schema.payment\",\"symbols\":[\"EUR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
