FROM azul/zulu-openjdk:21

ARG JAR_FILE=/target/ecommerce-product-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} product-service.jar

ENTRYPOINT ["java","-jar","product-service.jar", "--server.port=8080"]