FROM azul/zulu-openjdk:17.0.2

ARG JAR_FILE=/target/ecommerce-shopping-cart-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} shopping-cart-service.jar

ENTRYPOINT ["java","-jar","shopping-cart-service.jar"]