/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package ionutbalosin.training.ecommerce.event.schema.order;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class OrderCreatedEvent extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -543981668855440019L;

  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"OrderCreatedEvent\",\"namespace\":\"ionutbalosin.training.ecommerce.event.schema.order\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"products\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ProductEvent\",\"fields\":[{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"brand\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":\"float\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"discount\",\"type\":\"float\"}]}}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();

  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<OrderCreatedEvent> ENCODER =
      new BinaryMessageEncoder<OrderCreatedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderCreatedEvent> DECODER =
      new BinaryMessageDecoder<OrderCreatedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderCreatedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderCreatedEvent to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderCreatedEvent from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static OrderCreatedEvent fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID userId;
  private java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent> products;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public OrderCreatedEvent() {}

  /**
   * All-args constructor.
   *
   * @param userId The new value for userId
   * @param products The new value for products
   */
  public OrderCreatedEvent(
      java.util.UUID userId,
      java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent> products) {
    this.userId = userId;
    this.products = products;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return userId;
      case 1:
        return products;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
        new org.apache.avro.Conversions.UUIDConversion(), null, null
      };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        userId = (java.util.UUID) value$;
        break;
      case 1:
        products =
            (java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent>)
                value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   *
   * @return The value of the 'userId' field.
   */
  public java.util.UUID getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   *
   * @param value the value to set.
   */
  public void setUserId(java.util.UUID value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'products' field.
   *
   * @return The value of the 'products' field.
   */
  public java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent>
      getProducts() {
    return products;
  }

  /**
   * Sets the value of the 'products' field.
   *
   * @param value the value to set.
   */
  public void setProducts(
      java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent> value) {
    this.products = value;
  }

  /**
   * Creates a new OrderCreatedEvent RecordBuilder.
   *
   * @return A new OrderCreatedEvent RecordBuilder
   */
  public static ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder
      newBuilder() {
    return new ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder();
  }

  /**
   * Creates a new OrderCreatedEvent RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new OrderCreatedEvent RecordBuilder
   */
  public static ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder
      newBuilder(
          ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder other) {
    if (other == null) {
      return new ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder();
    } else {
      return new ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder(
          other);
    }
  }

  /**
   * Creates a new OrderCreatedEvent RecordBuilder by copying an existing OrderCreatedEvent
   * instance.
   *
   * @param other The existing instance to copy.
   * @return A new OrderCreatedEvent RecordBuilder
   */
  public static ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder
      newBuilder(ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent other) {
    if (other == null) {
      return new ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder();
    } else {
      return new ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder(
          other);
    }
  }

  /** RecordBuilder for OrderCreatedEvent instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderCreatedEvent>
      implements org.apache.avro.data.RecordBuilder<OrderCreatedEvent> {

    private java.util.UUID userId;
    private java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent>
        products;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(
        ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.products)) {
        this.products = data().deepCopy(fields()[1].schema(), other.products);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderCreatedEvent instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.products)) {
        this.products = data().deepCopy(fields()[1].schema(), other.products);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'userId' field.
     *
     * @return The value.
     */
    public java.util.UUID getUserId() {
      return userId;
    }

    /**
     * Sets the value of the 'userId' field.
     *
     * @param value The value of 'userId'.
     * @return This builder.
     */
    public ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder setUserId(
        java.util.UUID value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'userId' field has been set.
     *
     * @return True if the 'userId' field has been set, false otherwise.
     */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'userId' field.
     *
     * @return This builder.
     */
    public ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder
        clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'products' field.
     *
     * @return The value.
     */
    public java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent>
        getProducts() {
      return products;
    }

    /**
     * Sets the value of the 'products' field.
     *
     * @param value The value of 'products'.
     * @return This builder.
     */
    public ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder setProducts(
        java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent> value) {
      validate(fields()[1], value);
      this.products = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'products' field has been set.
     *
     * @return True if the 'products' field has been set, false otherwise.
     */
    public boolean hasProducts() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'products' field.
     *
     * @return This builder.
     */
    public ionutbalosin.training.ecommerce.event.schema.order.OrderCreatedEvent.Builder
        clearProducts() {
      products = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderCreatedEvent build() {
      try {
        OrderCreatedEvent record = new OrderCreatedEvent();
        record.userId =
            fieldSetFlags()[0] ? this.userId : (java.util.UUID) defaultValue(fields()[0]);
        record.products =
            fieldSetFlags()[1]
                ? this.products
                : (java.util.List<ionutbalosin.training.ecommerce.event.schema.order.ProductEvent>)
                    defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderCreatedEvent> WRITER$ =
      (org.apache.avro.io.DatumWriter<OrderCreatedEvent>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderCreatedEvent> READER$ =
      (org.apache.avro.io.DatumReader<OrderCreatedEvent>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }
}
