/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ionutbalosin.training.ecommerce.message.schema.order;
@org.apache.avro.specific.AvroGenerated
public enum OrderCurrency implements org.apache.avro.generic.GenericEnumSymbol<OrderCurrency> {
  EUR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderCurrency\",\"namespace\":\"ionutbalosin.training.ecommerce.message.schema.order\",\"symbols\":[\"EUR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
