FROM azul/zulu-openjdk:21

ARG JAR_FILE=/target/ecommerce-shipping-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} shipping-service.jar

ENTRYPOINT ["java","-jar","shipping-service.jar", "--server.port=8080"]